sonar.projectKey=ssd-quiz-2401154
sonar.projectName=SSD Quiz 2401154
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/ssl/**,**/reports/**,**/db/**,**/repos/**,**/www/**
sonar.javascript.lcov.reportPaths=
